// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRlr2BJs903g1z5baiIggE-B9e1t4ahI',
    appId: '1:437317535645:web:6df7a29475ab9c833f9174',
    messagingSenderId: '437317535645',
    projectId: 'moneylecdb',
    authDomain: 'moneylecdb.firebaseapp.com',
    databaseURL: 'https://moneylecdb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneylecdb.appspot.com',
    measurementId: 'G-C4K7K3VMC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcuSiGnHaFGg1VOh2LuARGWjPeYtdB6Nc',
    appId: '1:437317535645:android:901ab5335c4e900e3f9174',
    messagingSenderId: '437317535645',
    projectId: 'moneylecdb',
    databaseURL: 'https://moneylecdb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneylecdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFOeC2kxaq_eHHILldz4MClnA4qIYQIc',
    appId: '1:437317535645:ios:39362e15d20b90d23f9174',
    messagingSenderId: '437317535645',
    projectId: 'moneylecdb',
    databaseURL: 'https://moneylecdb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneylecdb.appspot.com',
    iosBundleId: 'com.example.moneyLec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFOeC2kxaq_eHHILldz4MClnA4qIYQIc',
    appId: '1:437317535645:ios:8e048dae567172503f9174',
    messagingSenderId: '437317535645',
    projectId: 'moneylecdb',
    databaseURL: 'https://moneylecdb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneylecdb.appspot.com',
    iosBundleId: 'com.example.moneyLec.RunnerTests',
  );
}
